name: Deploy Bicep to Azure

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment group create \
            --resource-group cs4037 \
            --template-file main.bicep \
            --parameters location=eastus
